config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  root "users#index"

  # users
  get "/users", to: "users#index", as: "users"
  get "/users/:user_id", to: "users#show", as: "user"

  # posts
  get "/users/:user_id/posts", to: "posts#index", as: "user_posts"
  get "/users/:user_id/posts/create", to: "posts#new", as: "new_post"
  post "/users/:user_id/posts/create", to: "posts#create", as: "create_post"
  get "/users/:user_id/posts/:post_id", to: "posts#show", as: "user_post"
  delete "/users/:user_id/posts/:post_id", to: "posts#destroy", as: "destroy_post"

  # comments
  get "/users/:user_id/posts/:post_id/comment", to: "comments#new", as: "new_comment"
  post "/users/:user_id/posts/:post_id/comment", to: "comments#create", as: "create_comment"
  delete "/users/:user_id/posts/:post_id/comment/:comment_id", to: "comments#destroy", as: "destroy_comment"

  # likes
  post "/users/:user_id/posts/:post_id/like", to: "likes#create", as: "add_like"


  ####### API

  # posts
  namespace :api do
    get "/users/:user_id/posts", to: "posts#index", as: "user_posts_api"
    get "/users/:user_id/posts/:post_id/comments", to: "comments#index", as: "post_comments_api"
    post "/users/:user_id/posts/:post_id/comments", to: "comments#create", as: "create_comment_api"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  after_initialize :init

  validates :name, length: { minimum: 2, maximum: 30 }, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def show_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def init
    return unless posts_counter.nil?

    self.posts_counter = 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params.require(:user_id))
    @recent_posts = @user.show_recent_posts
  end
end

app/views/users/index.erb
<%= stylesheet_link_tag "users" %>
<% @users.each do |user| %>
  <div class="user-row">
    <div class="profile-photo">
      <img class="placeholder-photo"></img>
    </div>
    <div class="user">
      <h2><%= link_to user.name, user_path(user), class: 'username' %></h2>
      <p>Number of posts: <%= user.posts_counter || 0 %></p>
    </div>
  </div>
<% end %>

app/views/users/show.erb
<%= stylesheet_link_tag "user" %>
<section class="user-row">
  <div class="profile-photo">
    <img class="placeholder-photo"></img>
  </div>
  <div class="user">
    <h2><%= @user.name %></h2>
    <p>Number of posts: <%= @user.posts_counter || 0 %></p>
    <% if can?(:manage, Post) && @user.id == current_user.id %>
      <%= button_to("add Post", new_post_path(@user), method: :get) %>
    <% end %>
  </div>
</section>
<section class="bio">
  <h4>Bio</h4>
  <p><%= @user.bio %></p>
</section>
<section class="posts">
  <% @recent_posts.each_with_index do |post, idx| %>
    <article class="post" id="<%= idx %>">
      <h3><%= link_to post.title, controller: "posts", action: "show", user_id: @user.id, post_id: post.id %></h3>
      <p><%= post.text %></p>
      <div class="reactions">
        <p>Comments: <%= post.comments_counter || 0 %>,&nbsp;</p>
        <p>Likes: <%= post.likes_counter || 0 %></p>
      </div>
    </article>
  <% end %>
</section>
<footer>
  <%= button_to("See all Post", user_posts_path(@user), method: :get, class: 'footer-btn') %>
</footer>