config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  root "users#index"

  # users
  get "/users", to: "users#index", as: "users"
  get "/users/:user_id", to: "users#show", as: "user"

  # posts
  get "/users/:user_id/posts", to: "posts#index", as: "user_posts"
  get "/users/:user_id/posts/create", to: "posts#new", as: "new_post"
  post "/users/:user_id/posts/create", to: "posts#create", as: "create_post"
  get "/users/:user_id/posts/:post_id", to: "posts#show", as: "user_post"
  delete "/users/:user_id/posts/:post_id", to: "posts#destroy", as: "destroy_post"

  # comments
  get "/users/:user_id/posts/:post_id/comment", to: "comments#new", as: "new_comment"
  post "/users/:user_id/posts/:post_id/comment", to: "comments#create", as: "create_comment"
  delete "/users/:user_id/posts/:post_id/comment/:comment_id", to: "comments#destroy", as: "destroy_comment"

  # likes
  post "/users/:user_id/posts/:post_id/like", to: "likes#create", as: "add_like"


  ####### API

  # posts
  namespace :api do
    get "/users/:user_id/posts", to: "posts#index", as: "user_posts_api"
    get "/users/:user_id/posts/:post_id/comments", to: "comments#index", as: "post_comments_api"
    post "/users/:user_id/posts/:post_id/comments", to: "comments#create", as: "create_comment_api"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user, foreign_key: :author_id
  after_destroy :decrement_posts_counter

  validates :title, length: { maximum: 250 }, allow_blank: false
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def show_recent_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end

  def increment_posts_counter
    user.increment :posts_counter
    user.save
  end

  def decrement_posts_counter
    user.decrement :posts_counter
    user.save
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  def index
    @posts = Post.all.where(author_id: params.require(:user_id))
    render json: @posts, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts).find_by(id: params.require(:user_id))
  end

  def show
    @post = Post.find_by(id: params.require(:post_id))
    @user_id = params.require(:user_id)
  end

  def new
    @user_id = current_user.id
  end

  def create
    @post = Post.new(
      title: post_params[:title],
      text: post_params[:text],
      user: current_user,
      comments_counter: 0,
      likes_counter: 0
    )

    if @post.save
      @post.increment_posts_counter
      redirect_to user_posts_path current_user.id
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user_id = params[:user_id]
    Post.find_by(id: params[:post_id]).destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/destroy.erb
<p>Post is successfully deleted!</p>
<p>You are being <%= link_to 'redirected', "/users/#{@user_id}/posts" %><span id="timeout" > 5</span></p>
<script>
  window.onload = function () {
    const span = document.querySelector("#timeout")
    let time = 5
    setInterval(() => {
        span.innerText = ` ${time -= 1}`
    }, 1000)
    setTimeout(() => {
        clearInterval()
        window.location.href = "/users/<%= @user_id %>/posts"
    }, 5000)
  }
</script>

app/views/posts/index.erb
<%= stylesheet_link_tag "posts" %>
<section class="user-row">
  <div class="profile-photo">
    <img class="placeholder-photo"></img>
  </div>
  <div class="user">
    <h2><%= @user.name %></h2>
    <p>Number of posts: <%= @user.posts_counter || 0 %></p>
    <button>
      <%= link_to 'add Post', controller: 'posts', action: 'new' %>
    </button>
  </div>
</section>
<section class="posts">
  <% @user.posts.each_with_index do |post, idx| %>
    <article class="post" id="<%= idx %>">
      <h3><%= link_to post.title, controller: "posts", action: "show", user_id: @user.id, post_id: post.id %></h3>
      <p><%= post.text %></p>
      <div class="reactions">
        <p>Comments: <%= post.comments_counter || 0 %>,&nbsp;</p>
        <p>Likes: <%= post.likes_counter || 0 %></p>
      </div>
      <div class="comments">
        <% post.show_recent_comments.each do |comment| %>
          <div class="comment">
            <p><strong><%= comment.user.name %></strong>: <%= comment.text %></p>
          </div>
        <% end %>
      </div>
    </article>
  <% end %>
  <div class="pagination">pagination</div>
</section>

app/views/posts/new.erb
<%= stylesheet_link_tag "form" %>
<%= form_with model: @post, url: "/users/#{@user_id}/posts/create", class: "post-form" do |form| %>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
  <%= form.label :text %><br>
  <%= form.text_area :text %>
  <button type="submit">Add post</button>
<% end %>

app/views/posts/show.erb
<%= stylesheet_link_tag "post" %>
<article class="post" id="<%= @post.id %>">
  <div class="post-title">
    <h3><%= @post.title %>&nbsp;<span class="username">by <%= @post.user.name %></span></h3>
  </div>
  <div class="reactions">
    <p>Comments: <%= @post.comments_counter || 0 %>,&nbsp;</p>
    <p>Likes: <%= @post.likes_counter || 0 %></p>
  </div>
  <div class="actions">
    <%= button_to("add Comment", new_comment_path(@user_id, @post), method: :get) %>
    <%= button_to("Like", add_like_path(@user_id, @post), method: :post) %>
    <% if can? :destroy, @post %>
      <%= button_to("Delete post", destroy_post_path(@user_id, @post), method: :delete) %>
    <% end %>
  </div>
  <p><%= @post.text %></p>
  <div class="comments">
    <% @post.comments.each do |comment| %>
      <div class="comment">
        <p><strong><%= comment.user.name %></strong>: <%= comment.text %></p>
        <% if can? :delete, comment %>
          <%= button_to("Delete comment", destroy_comment_path(@user_id, @post, comment), method: :delete) %>
        <% end %>
      </div>
    <% end %>
  </div>
</article>